package it.water.user.api;

import it.water.core.api.repository.BaseRepository;
import it.water.core.interceptors.annotations.*;
import it.water.user.model.UserCompany;

import java.util.List;

/**
 * @Generated by Water Generator
 * Interface component for UserCompany Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
public interface UserCompanyRepository extends BaseRepository<UserCompany> {

    /**
     * @param userId    user id
     * @param companyId opaque company id
     * @return true if a (userId, companyId) membership row exists
     */
    boolean existsByUserAndCompany(long userId, long companyId);

    /**
     * @param userId user id
     * @return the companyId of the user's primary membership, or null if none is flagged primary
     */
    Long findPrimaryCompanyId(long userId);

    /**
     * @param userId user id
     * @return the list of company ids the user is a member of (possibly empty, never null)
     */
    List<Long> findCompanyIdsByUser(long userId);

    /**
     * @param companyId opaque company id
     * @return the distinct list of user ids that are members of the given company (possibly empty, never null).
     * Used by the tenant enforcement seam (TenantMembershipResolver) to scope M:N tenant queries.
     */
    List<Long> findUserIdsByCompany(long companyId);

    /**
     * @param companyId opaque company id
     * @return users whose primary membership points to the given company
     */
    List<Long> findPrimaryUserIdsByCompany(long companyId);
}
