package it.water.user.api;

import it.water.core.api.service.BaseEntityApi;

import it.water.user.model.UserCompany;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface UserCompanyApi extends BaseEntityApi<UserCompany> {

}