package it.water.user.api;

import it.water.core.api.service.BaseEntitySystemApi;

import it.water.user.model.UserCompany;

import java.util.List;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of UserCompanySystemApi is to validate the entity and pass it to the persistence layer.
 *
 */
public interface UserCompanySystemApi extends BaseEntitySystemApi<UserCompany> {

    /**
     * @param userId    user id
     * @param companyId opaque company id
     * @return true if a (userId, companyId) membership exists. Internal use (login gate).
     */
    boolean existsByUserAndCompany(long userId, long companyId);

    /**
     * @param userId user id
     * @return the companyId of the user's primary membership, or null if none.
     */
    Long findPrimaryCompanyId(long userId);

    /**
     * @param userId user id
     * @return the company ids the user is a member of (possibly empty, never null).
     */
    List<Long> findCompanyIdsByUser(long userId);

    /**
     * @param companyId opaque company id
     * @return the distinct user ids that are members of the given company (possibly empty, never null).
     * Internal use (tenant enforcement seam).
     */
    List<Long> findUserIdsByCompany(long companyId);
}