package it.water.user.service;

import it.water.user.api.*;
import it.water.user.model.*;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.*;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import lombok.*;

import java.util.List;


/**
 * @Generated by Water Generator
 * System Service Api Class for UserCompany entity.
 *
 */
@FrameworkComponent
public class UserCompanySystemServiceImpl extends BaseEntitySystemServiceImpl<UserCompany> implements UserCompanySystemApi {
    @Inject
    @Getter
    @Setter
    private UserCompanyRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public UserCompanySystemServiceImpl() {
        super(UserCompany.class);
    }

    @Override
    public boolean existsByUserAndCompany(long userId, long companyId) {
        return repository.existsByUserAndCompany(userId, companyId);
    }

    @Override
    public Long findPrimaryCompanyId(long userId) {
        return repository.findPrimaryCompanyId(userId);
    }

    @Override
    public List<Long> findCompanyIdsByUser(long userId) {
        return repository.findCompanyIdsByUser(userId);
    }

    @Override
    public List<Long> findUserIdsByCompany(long companyId) {
        return repository.findUserIdsByCompany(companyId);
    }

}