package it.water.user.service;

import it.water.user.api.*;
import it.water.user.model.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.*;


/**
 * @Generated by Water Generator
 * Service Api Class for UserCompany entity.
 *
 */
@FrameworkComponent
public class UserCompanyServiceImpl extends BaseEntityServiceImpl<UserCompany> implements UserCompanyApi {

    @Inject
    @Getter
    @Setter
    private UserCompanySystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public UserCompanyServiceImpl() {
        
        super(UserCompany.class);
    }
    
    //todo: add custom logic here...
    //use getLog to retrieve Logger instance automatically instantiated for this class
}
