@startuml

set namespaceSeparator none

rectangle "User-api" as userApiModule #DAE8FC{
  package it.water.user.api  as ApiPackage #DAE8FC{
     interface UserApi {
     }
     interface UserRepository {
     
     }
     interface UserSystemApi {
     
     }
     
     package options as ApiOptionsPackage #DAE8FC{
        interface UserOptions {
        }
     }
     
     package rest as ApiRestPackage #DAE8FC{
        interface UserRestApi { 
        }
     }   
  }
}

package "User-model" as userModelModule #FFE6CC {
  package it.water.user  as ModelPackage #FFE6CC{
    package actions as ActionsPackage #FFE6CC {
        class UserActions {
        
        }
     }
     package model as ModelPackage #FFE6CC{
        class WaterUser {
        
        }
     }
  }
}

package "User-service" as UserServiceModule #D5E8D4 {
  package it.water.user  as ServicePackage #D5E8D4{
    package repository as RepositoryPackage #D5E8D4 {
        class UserRepositoryImpl
     }
     package service as ServiceImplPackage #D5E8D4{
        package rest as ServiceRestPackage #D5E8D4{
           class UserRestControllerImpl
        }
        class UserOptionsImpl
        class UserServiceImpl
        class UserSystemServiceImpl
     }
  }

}

package "User-service-spring" as UserServiceSpring #FFF2CC {

}


@enduml