package it.water.user.model;

import it.water.repository.jpa.model.AbstractJpaEntity;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.api.permission.*;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.permission.annotations.DefaultRoleAccess;
import lombok.*;
import it.water.core.validation.annotations.*;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;

import com.fasterxml.jackson.annotation.JsonView;


/**
 * @Generated by Water Generator
 * UserCompany Entity Class.
 *
 * Membership join between a user and a company (M:N). companyId is an opaque Long: there is NO JPA
 * relation towards the Company entity (tenant isolation lives in the User domain module). The primary
 * flag marks the default company selected at login when none is explicitly requested.
 */
//JPA
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"userId", "companyId"}))
@Access(AccessType.FIELD)
//Lombok
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@RequiredArgsConstructor
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString
@EqualsAndHashCode(of = {"userId", "companyId"}, callSuper = true)
//Actions and default roles access
@AccessControl(availableActions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE},
rolesPermissions = {
       //Admin role can do everything
        @DefaultRoleAccess(roleName = UserCompany.DEFAULT_MANAGER_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE}),
        //Viwer has read only access
        @DefaultRoleAccess(roleName = UserCompany.DEFAULT_VIEWER_ROLE, actions = {CrudActions.FIND, CrudActions.FIND_ALL}),
        //Editor can do anything but remove
        @DefaultRoleAccess(roleName = UserCompany.DEFAULT_EDITOR_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL})
})public class UserCompany extends AbstractJpaEntity implements ProtectedEntity  {

    public static final String DEFAULT_MANAGER_ROLE = "UserCompanyManager";
    public static final String DEFAULT_VIEWER_ROLE = "UserCompanyViewer";
    public static final String DEFAULT_EDITOR_ROLE = "UserCompanyEditor";

    /**
     * Id of the user this membership belongs to.
     */
    @NotNull
    @NotNullOnPersist
    @NonNull
    @JsonView(WaterJsonView.Extended.class)
    private Long userId;

    /**
     * Opaque id of the company the user is a member of. No JPA relation towards Company.
     */
    @NotNull
    @NotNullOnPersist
    @NonNull
    @JsonView(WaterJsonView.Extended.class)
    private Long companyId;

    /**
     * Marks the default company selected at login when none is explicitly requested.
     * Column name avoids the SQL reserved word "primary".
     */
    @Column(name = "is_primary", columnDefinition = "BOOLEAN DEFAULT FALSE")
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private boolean primary;
}
