package it.water.user.repository;

import it.water.user.api.*;
import it.water.user.model.*;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.repository.query.Query;
import it.water.core.api.repository.query.QueryBuilder;
import it.water.core.interceptors.annotations.*;
import it.water.repository.entity.model.exceptions.NoResultException;
import it.water.repository.jpa.WaterJpaRepositoryImpl;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * @Generated by Water Generator
 * Repository Class for UserCompany entity.
 *
 */
@FrameworkComponent
public class UserCompanyRepositoryImpl extends WaterJpaRepositoryImpl<UserCompany> implements UserCompanyRepository {

    private static final String USERCOMPANY_PERSISTENCE_UNIT = "user-persistence-unit";
    private static final String USER_ID_FIELD = "userId";
    private static final String COMPANY_ID_FIELD = "companyId";
    private static final String PRIMARY_FIELD = "primary";

    public UserCompanyRepositoryImpl() {
        super(UserCompany.class, USERCOMPANY_PERSISTENCE_UNIT);
    }

    @Override
    public boolean existsByUserAndCompany(long userId, long companyId) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field(USER_ID_FIELD).equalTo(userId).and(qb.field(COMPANY_ID_FIELD).equalTo(companyId));
        return this.countAll(q) > 0;
    }

    @Override
    public Long findPrimaryCompanyId(long userId) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field(USER_ID_FIELD).equalTo(userId).and(qb.field(PRIMARY_FIELD).equalTo(true));
        try {
            UserCompany membership = this.find(q);
            return (membership != null) ? membership.getCompanyId() : null;
        } catch (NoResultException e) {
            return null;
        }
    }

    @Override
    public List<Long> findCompanyIdsByUser(long userId) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field(USER_ID_FIELD).equalTo(userId);
        PaginableResult<UserCompany> result = this.findAll(-1, -1, q, null);
        List<Long> companyIds = new ArrayList<>();
        result.getResults().forEach(membership -> companyIds.add(membership.getCompanyId()));
        return companyIds;
    }

    @Override
    public List<Long> findUserIdsByCompany(long companyId) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field(COMPANY_ID_FIELD).equalTo(companyId);
        PaginableResult<UserCompany> result = this.findAll(-1, -1, q, null);
        return result.getResults().stream()
                .map(UserCompany::getUserId)
                .distinct()
                .collect(Collectors.toList());
    }

    @Override
    public List<Long> findPrimaryUserIdsByCompany(long companyId) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field(COMPANY_ID_FIELD).equalTo(companyId)
                .and(qb.field(PRIMARY_FIELD).equalTo(true));
        PaginableResult<UserCompany> result = this.findAll(-1, -1, q, null);
        return result.getResults().stream()
                .map(UserCompany::getUserId)
                .distinct()
                .collect(Collectors.toList());
    }
}
